# Generated by Django 3.2.6 on 2021-08-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0008_alter_employee_employeename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmployeeName',
            field=models.CharField(max_length=50),
        ),
    ]
