# Generated by Django 3.2.6 on 2021-08-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(default='', max_length=50)),
                ('prodetail', models.CharField(default='', max_length=50)),
                ('seller', models.CharField(default='', max_length=50)),
                ('manufacturer', models.CharField(default='', max_length=50)),
                ('manudate', models.DateField(default='')),
                ('expirydate', models.DateField(default='')),
                ('price', models.IntegerField(default='')),
            ],
        ),
    ]
