# Generated by Django 3.2.6 on 2021-08-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(default='', max_length=50)),
                ('shopadd', models.CharField(default='', max_length=50)),
                ('website', models.CharField(default='', max_length=50)),
                ('phone', models.BigIntegerField(default=0)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('confirmpass', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
