# Generated by Django 3.2.6 on 2021-08-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.BigIntegerField(default='')),
                ('dateofbirth', models.DateField(default='')),
                ('age', models.IntegerField(default='')),
                ('aadhar', models.IntegerField(default='')),
            ],
        ),
    ]
