# Generated by Django 3.2.6 on 2021-08-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductID', models.IntegerField()),
                ('Description', models.CharField(max_length=50)),
                ('ProductPrice', models.IntegerField()),
            ],
        ),
    ]
